### PR TITLE
Update campaign-request.md

### PR DESCRIPTION
**Pull request by Caerlower**
It is a request for making some awesome quests for our new and awesome web developers starting out they journey.

### CODE REVIEW

**Review by AbbeyIT — COMMENTED** [review]
This should be in the Issues tab. You shouldn't pull a request and edit the template because that one is provided for the issue for people to guide on what to write in the said template. Please read the instructions again in the quest.

**Comment by Caerlower** [comment]
Hey I am sorry for that I have written it in the issue tab but now should I remove the pull back request.

**Comment by AbbeyIT** [comment]
@ExpertManav It's fine. It's okay to close this pull request now.

**Comment by Caerlower** [comment]
I have closed it @AbbeyIT

**Pull request closed without merging**
